import mongoose from "mongoose";

const ResumeSchema = new mongoose.Schema(
    {
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
            index: true
        },

        resumeName: {
            type: String,
            required: true,
            trim: true
        },

        targetRole: {
            type: String,
            default: ""
        },

        originalFileName: {
            type: String,
            required: true
        },

        fileUrl: {
            type: String,
            required: true
        },

        resumeText: {
            type: String,
            required: true
        },

        // Structured resume generated by Python LLM
        parsedData: {
            type: mongoose.Schema.Types.Mixed,
            default: {}
        },

        // 384-dimensional SentenceTransformer embedding
        embedding: {
            type: [Number],
            default: []
        }
    },
    {
        timestamps: true
    }
);

export const Resume = mongoose.model(
    "Resume",
    ResumeSchema
);